In [3]:
import networkx as nx
import matplotlib.pyplot as plt
import numpy as np
import time

n_lower = 0; n_upper = 2
num = np.unique(np.logspace(n_lower, n_upper, num = n_upper+1, base=10, dtype = int))
prob = np.arange(0.1, 1, 0.1)
num_graphs = 10
print(num)
# g1 = nx.erdos_renyi_graph(10, 0.5, seed = None)
# g2 = nx.erdos_renyi_graph(10, 0.5)

g1 = nx.erdos_renyi_graph(7, 0.5, seed = 2)
g2 = nx.erdos_renyi_graph(5, 0.5, seed = 3)
# nx.draw(g1, with_labels=True)
# plt.show()
a1 = nx.adjacency_matrix(g1)
A1 = np.matrix(a1.toarray())
a2 = nx.adjacency_matrix(g2)
A2 = np.matrix(a2.toarray())
print(A1)

degrees_1 = np.array([deg for _, deg in g1.degree()])
degrees_1 = np.where(degrees_1 == 0, 1, degrees_1)
degrees_2 = np.array([deg for _, deg in g2.degree()])
degrees_2 = np.where(degrees_2 == 0, 1, degrees_2)

D1 = np.diag(degrees_1)
D2 = np.diag(degrees_2)
print("")
print(D1)
# print(np.sqrt(D))

L1 = D1 - A1   # graph Laplacian
L2 = D2 - A2

D_sqrt_inv_1 = np.diag(1 / np.sqrt(degrees_1))
norm_L1 = D_sqrt_inv_1 @ L1 @ D_sqrt_inv_1   # normalized Laplacian

D_sqrt_inv_2 = np.diag(1 / np.sqrt(degrees_2))
norm_L2 = D_sqrt_inv_2 @ L2 @ D_sqrt_inv_2
# print(norm_L1)

adj_frob = np.linalg.norm(A1 - A2, 'fro') # Frobenius norm
# print(adj_frob)

[  1  10 100]
[[0 0 0 1 1 0 0]
 [0 0 0 1 0 0 0]
 [0 0 0 1 1 1 0]
 [1 1 1 0 0 0 0]
 [1 0 1 0 0 1 1]
 [0 0 1 0 1 0 1]
 [0 0 0 0 1 1 0]]

[[2 0 0 0 0 0 0]
 [0 1 0 0 0 0 0]
 [0 0 3 0 0 0 0]
 [0 0 0 3 0 0 0]
 [0 0 0 0 4 0 0]
 [0 0 0 0 0 3 0]
 [0 0 0 0 0 0 2]]


ValueError: operands could not be broadcast together with shapes (7,7) (5,5) 

In [80]:
adj_e1 = np.linalg.eig(A1)[0]
adj_e1 = adj_e1[np.argsort(adj_e1)]
adj_e2 = np.linalg.eig(A2)[0]
adj_e2 = adj_e2[np.argsort(adj_e2)]

lap_e1 = np.linalg.eig(L1)[0]
lap_e1 = lap_e1[np.argsort(lap_e1)]
lap_e2 = np.linalg.eig(L2)[0]
lap_e2 = lap_e2[np.argsort(lap_e2)]
# print(len(adj_e1))
# print(len(lap_e1))
if len(adj_e1) == len(adj_e2) and len(lap_e1) == len(lap_e2):
    adj_spec_dist = np.sum(np.abs(adj_e1 - adj_e2))
    lap_spec_dist = np.sum(np.abs(lap_e1 - lap_e2))

print(adj_spec_dist)
print(lap_spec_dist)

1.2197159474978783
1.4049058697822805


In [ ]:
# numpy.random.binomial
print(np.random.binomial(10, 0.5, 3)) # will generate a vector of n choose 2 entries, each with a probablity that its 1 or 0
# isomorphism
# so each vector generated randomly from the binomial distribution is a row in our adjacency matrix
# where the first row is n - 1 entries
# second row is n - 2 entries
# ...
# second to last row is 2 entries
# and last row is 1 entry 
# and these rows correspond to our upper right hand triangle matrix

# and stacking these vectors on top of each other then mirroring by symmetry would give a complete adjacency matrix



[5 6 5]


In [ ]:
# For uniform distribution, the points in the point cloud are uniformly/evenly spread across our metric space [0,1]^d.
